mod_dir = mod_directory()

sound_add(mod_dir + "/sound.ogg", "sndDiscord")

function_add("useTestPotion", '
	player = argument0
	
	if (player.active_item == "eggplant_potion") {
		player.hp += 6
		player.image_blend = make_color_rgb(100, 0, 110)
		
		if (player.hp > player.max_hp) {
			player.hp = player.max_hp
		}
		
		player.poison = 0
		player.bleed = 0
		player.blind = 0
	}
');

callback_add("active_item", "useTestPotion")

function_add("pickPerk", '
	perk = argument0
	player = argument1
	
	if (perk == "sack" || perk == "discord") {
		player.hp = player.max_hp
		sound_play_pitch(sndTextboxWrite, 0.1)
	}
');

callback_add("pick_perk", "pickPerk")

function_add("dropdyn", '
	dynamite = instance_create(argument1.x, argument1.y, asset_get_index("Dynamite"))
	dynamite.image_speed = 0.2
');

callback_add("entity_hit", "dropdyn")

function_add("myStep", '
	player = player_get()
	
	if (instance_exists(player) && get_perk("sack", player.index)) {
		if (random(1) < 0.2) {
			bullet = instance_create(player.x, player.y, asset_get_index("RobotBlast"))
			
			bullet.speed = 5 + random(2)
			bullet.direction = random(360)
			bullet.team = player.team
			bullet.creator = player
			
			bullet.image_angle = bullet.direction
		}
	}
	
	if (instance_exists(player) && get_perk("discord", player.index) && !sound_is_playing(sndDiscord)) {
		sound_loop(sndDiscord)
		sound_stop_music()
	}
');

callback_add("step", "myStep")